# -*- coding: utf-8 -*-
"""Rachel_Phung_MIS373_A1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xx80jEbHN_dEtFmJr8a_9cl6_lTFWCjK

## MIS373 Assignment 1 - Airbnb Reviews

Student name: Ngoc Anh (Rachel) Phung

Student ID: 224598824

## Loading Data
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install vaderSentiment

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

listings = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/MIS373/listings.csv')
reviews = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/MIS373/reviews.csv')

"""## Cleaning Data"""

listings.head()

listings.info()

listings = listings.drop(columns=['neighbourhood_group', 'price', 'license'])

listings.describe()

reviews.head()

reviews.info()

"""## Question A - Lexicon-Based Sentiment Analysis (VADER)

Among the 10 most popular Airbnb neighbourhoods in Victoria, which neighbourhoods show the highest and lowest levels of overall guest satisfaction based on review sentiment?
"""

# "Most popular" = neighbourhood with highest total number of reviews across all its properties
neighbourhood_popularity = (
    listings.groupby('neighbourhood')['number_of_reviews']
    .sum()
    .sort_values(ascending=False)
    .reset_index()
    .rename(columns={'number_of_reviews': 'total_reviews'})
)

top10_neighbourhoods = neighbourhood_popularity.head(10)
print(top10_neighbourhoods)

# Filter listings to only those in the top 10 neighbourhoods
top10_names = top10_neighbourhoods['neighbourhood'].tolist()
top10_listings = listings[listings['neighbourhood'].isin(top10_names)][['id', 'neighbourhood']]

print(f"Properties in top 10 neighbourhoods: {len(top10_listings)}")

# Drop null comments first
reviews_clean = reviews.dropna(subset=['comments']).copy()

# Merge reviews with listing neighbourhood info
reviews_merged = reviews_clean.merge(
    top10_listings,
    left_on='listing_id',
    right_on='id',
    how='inner'
)

print(f"Reviews matched to top 10 neighbourhoods: {len(reviews_merged)}")
print(reviews_merged[['listing_id', 'neighbourhood', 'comments']].head(3))

analyzer = SentimentIntensityAnalyzer()

# Apply VADER to each comment — extract the compound score
reviews_merged['compound_score'] = reviews_merged['comments'].apply(
    lambda text: analyzer.polarity_scores(str(text))['compound']
)

# Classify sentiment for reference
def classify_sentiment(score):
    if score >= 0.05:
        return 'Positive'
    elif score <= -0.05:
        return 'Negative'
    else:
        return 'Neutral'

reviews_merged['sentiment_label'] = reviews_merged['compound_score'].apply(classify_sentiment)

print(reviews_merged[['neighbourhood', 'compound_score', 'sentiment_label']].head())
print("\nSentiment distribution:\n", reviews_merged['sentiment_label'].value_counts())

# Calculate mean compound score and sentiment breakdown per neighbourhood
sentiment_summary = reviews_merged.groupby('neighbourhood').agg(
    review_count=('compound_score', 'count'),
    mean_compound=('compound_score', 'mean'),
    pct_positive=('sentiment_label', lambda x: (x == 'Positive').mean() * 100),
    pct_negative=('sentiment_label', lambda x: (x == 'Negative').mean() * 100),
    pct_neutral=('sentiment_label', lambda x: (x == 'Neutral').mean() * 100)
).reset_index()

# Sort by mean compound score
sentiment_summary = sentiment_summary.sort_values('mean_compound', ascending=False).round(4)
print(sentiment_summary.to_string())

plt.figure(figsize=(12, 7))

# Dynamic coloring logic
colors = ['green' if x == sentiment_summary['mean_compound'].max()
          else 'red' if x == sentiment_summary['mean_compound'].min()
          else 'orange' for x in sentiment_summary['mean_compound']]

# Create the bar plot
ax = plt.gca()
bars = ax.bar(sentiment_summary['neighbourhood'], sentiment_summary['mean_compound'], color=colors)

# Display the numbers above each bar
ax.bar_label(bars, fmt='%.2f', padding=3)

# Add the average line
plt.axhline(y=sentiment_summary['mean_compound'].mean(), color='black', linestyle='--', label=f"Average ({sentiment_summary['mean_compound'].mean():.2f})")

plt.xticks(rotation=45, ha='right')
plt.title('Mean VADER Compound Sentiment Score by Neighbourhood\n(Top 10 Most Popular in Victoria)', fontsize=15)
plt.ylabel('Mean Compound Score (-1 to +1)')
plt.xlabel('Neighbourhood')
plt.legend()
plt.tight_layout()

plt.savefig('sentiment_by_neighbourhood_labeled.png', dpi=150)
plt.show()

fig, ax = plt.subplots(figsize=(12, 6))

# Sort by mean compound for consistency
df_plot = sentiment_summary.sort_values('mean_compound', ascending=False)

ax.bar(df_plot['neighbourhood'], df_plot['pct_positive'], label='Positive', color='#2ecc71')
ax.bar(df_plot['neighbourhood'], df_plot['pct_neutral'], bottom=df_plot['pct_positive'], label='Neutral', color='#f39c12')
ax.bar(df_plot['neighbourhood'], df_plot['pct_negative'],
       bottom=df_plot['pct_positive'] + df_plot['pct_neutral'], label='Negative', color='#e74c3c')

ax.set_xlabel('Neighbourhood')
ax.set_ylabel('Percentage of Reviews (%)')
ax.set_title('Sentiment Distribution by Neighbourhood (Top 10 in Victoria)', fontsize=13)
ax.legend()
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.savefig('sentiment_distribution.png', dpi=150)
plt.show()

# Clean output table for report
report_table = sentiment_summary[['neighbourhood', 'review_count', 'mean_compound', 'pct_positive', 'pct_negative']].copy()
report_table.columns = ['Neighbourhood', 'Reviews Analysed', 'Mean Compound Score', '% Positive', '% Negative']
report_table = report_table.sort_values('Mean Compound Score', ascending=False)
print(report_table.to_string(index=False))

"""## Question B - Aspect-Level Sentiment Analysis

What aspects of the Airbnb guest experience (including but not limited to location, cleanliness, amenities, and value for money) are most strongly associated with guest dissatisfaction in Victoria, and

Why are these aspects likely to generate negative experiences?
"""

reviews_clean = reviews.dropna(subset=['comments']).copy()
reviews_clean['comments_lower'] = reviews_clean['comments'].str.lower()

analyzer = SentimentIntensityAnalyzer()
reviews_clean['compound'] = reviews_clean['comments'].apply(
    lambda x: analyzer.polarity_scores(str(x))['compound']
)

# Define "dissatisfied" reviews: compound score <= -0.05 (VADER standard threshold)
negative_reviews = reviews_clean[reviews_clean['compound'] <= -0.05].copy()
print(f"Total reviews: {len(reviews_clean)}")
print(f"Negative reviews (compound ≤ -0.05): {len(negative_reviews)} ({len(negative_reviews)/len(reviews_clean)*100:.1f}%)")

# Each aspect has keywords that indicate it is being discussed
# These are chosen to reflect common Airbnb review language
aspect_keywords = {
    'Cleanliness':         ['clean', 'dirty', 'dust', 'stain', 'smell', 'smelly',
                            'filthy', 'mold', 'mould', 'grubby', 'hygiene', 'tidy'],
    'Host Communication':  ['host', 'communication', 'responsive', 'response',
                            'helpful', 'reply', 'contact', 'message', 'check-in',
                            'check in', 'instructions'],
    'Value for Money':     ['value', 'price', 'expensive', 'cheap', 'worth',
                            'overpriced', 'affordable', 'cost', 'money', 'fee'],
    'Amenities/Facilities':['wifi', 'internet', 'kitchen', 'bathroom', 'shower',
                            'bed', 'parking', 'amenities', 'heating', 'air con',
                            'aircon', 'towel', 'linen', 'appliance'],
    'Noise & Comfort':     ['noise', 'noisy', 'quiet', 'loud', 'sound', 'sleep',
                            'comfortable', 'uncomfortable', 'disturb', 'thin wall'],
    'Listing Accuracy':    ['photos', 'listing', 'described', 'accurate', 'expect',
                            'actual', 'misleading', 'reality', 'different from',
                            'nothing like', 'false', "not what"],
    'Location':            ['location', 'transport', 'tram', 'train', 'bus',
                            'central', 'far', 'access', 'distance', 'suburb',
                            'walk', 'parking'],
    'Safety/Security':     ['safe', 'unsafe', 'security', 'lock', 'door', 'key',
                            'dangerous', 'area', 'neighbourhood'],
}

def detect_aspects(text, aspect_keywords):
    detected = []
    for aspect, keywords in aspect_keywords.items():
        if any(kw in text for kw in keywords):
            detected.append(aspect)
    return detected

reviews_clean['aspects'] = reviews_clean['comments_lower'].apply(
    lambda x: detect_aspects(x, aspect_keywords)
)
negative_reviews['aspects'] = negative_reviews['comments_lower'].apply(
    lambda x: detect_aspects(x, aspect_keywords)
)

total = len(reviews_clean)
total_neg = len(negative_reviews)

aspect_stats = []
for aspect in aspect_keywords:
    all_count = reviews_clean['aspects'].apply(lambda x: aspect in x).sum()
    neg_count = negative_reviews['aspects'].apply(lambda x: aspect in x).sum()

    pct_all = all_count / total * 100
    pct_neg = neg_count / total_neg * 100
    # Dissatisfaction ratio: how much MORE likely is this aspect in negative vs all reviews
    ratio = pct_neg / pct_all if pct_all > 0 else 0

    aspect_stats.append({
        'Aspect': aspect,
        'Mentions (All Reviews)': all_count,
        'Mentions (Negative Reviews)': neg_count,
        '% of All Reviews': round(pct_all, 1),
        '% of Negative Reviews': round(pct_neg, 1),
        'Dissatisfaction Ratio': round(ratio, 2)
    })

aspect_df = pd.DataFrame(aspect_stats).sort_values('% of Negative Reviews', ascending=False)
print(aspect_df.to_string(index=False))

fig, ax = plt.subplots(figsize=(13, 6))

x = range(len(aspect_df))
width = 0.4

bars1 = ax.bar([i - width/2 for i in x], aspect_df['% of All Reviews'],
               width=width, label='% of All Reviews', color='#3498db', alpha=0.8)
bars2 = ax.bar([i + width/2 for i in x], aspect_df['% of Negative Reviews'],
               width=width, label='% of Negative Reviews', color='#e74c3c', alpha=0.8)

ax.set_xticks(list(x))
ax.set_xticklabels(aspect_df['Aspect'], rotation=35, ha='right')
ax.set_ylabel('% of Reviews Mentioning Aspect')
ax.set_title('Aspect Mentions: All Reviews vs Negative Reviews\n(Victoria Airbnb, N=100,000)', fontsize=13)
ax.legend()
plt.tight_layout()
plt.savefig('aspect_comparison.png', dpi=150)
plt.show()

import matplotlib.patches as mpatches

# This is your KEY chart — shows which aspects are MOST associated with dissatisfaction
ratio_df = aspect_df.sort_values('Dissatisfaction Ratio', ascending=True)

colors = ['#e74c3c' if r >= 1.2 else '#f39c12' if r >= 1.0 else '#2ecc71'
          for r in ratio_df['Dissatisfaction Ratio']]

fig, ax = plt.subplots(figsize=(10, 6))
ax.barh(ratio_df['Aspect'], ratio_df['Dissatisfaction Ratio'], color=colors)
ax.axvline(x=1.0, color='black', linestyle='--', linewidth=1.2, label='Baseline (ratio = 1.0)')
ax.set_xlabel('Dissatisfaction Ratio\n(% in Negative Reviews ÷ % in All Reviews)')
ax.set_title('Aspects Most Over-Represented in Negative Reviews\n(Dissatisfaction Ratio)', fontsize=13)
ax.legend()

red_patch = mpatches.Patch(color='#e74c3c', label='Strongly over-represented (≥1.2)')
orange_patch = mpatches.Patch(color='#f39c12', label='Slightly over-represented (1.0–1.2)')
green_patch = mpatches.Patch(color='#2ecc71', label='Under-represented (<1.0)')
ax.legend(handles=[red_patch, orange_patch, green_patch], loc='lower right')

plt.tight_layout()
plt.savefig('dissatisfaction_ratio.png', dpi=150)
plt.show()

#Sample complaint

for aspect in aspect_df['Aspect'].tolist():
    mask = negative_reviews['aspects'].apply(lambda x: aspect in x)
    samples = negative_reviews[mask]['comments'].dropna().head(3).tolist()
    print(f"\n=== {aspect} — Sample Complaints ===")
    for s in samples:
        print(f"  • {s[:200]}")

# Merge negative reviews with listings to get neighbourhood information
monash_negative = negative_reviews.merge(
    listings[listings['neighbourhood'] == 'Monash'][['id', 'neighbourhood']],
    left_on='listing_id',
    right_on='id',
    how='inner'
)

# Count mentions for each aspect in Monash negative reviews
monash_aspect_counts = {}
for aspect in aspect_keywords:
    count = monash_negative['aspects'].apply(lambda x: aspect in x).sum()
    monash_aspect_counts[aspect] = count

# Convert to DataFrame for display
monash_aspect_df = pd.DataFrame(list(monash_aspect_counts.items()), columns=['Aspect', 'Mentions'])
monash_aspect_df = monash_aspect_df.sort_values('Mentions', ascending=False)

print(f"Total negative reviews in Monash: {len(monash_negative)}")
display(monash_aspect_df)

import matplotlib.pyplot as plt

# Create the bar chart for Monash specific negative reviews
plt.figure(figsize=(10, 6))
plt.bar(monash_aspect_df['Aspect'], monash_aspect_df['Mentions'], color='orange')

plt.title('Aspect Mentions in Negative Reviews: Monash Neighbourhood', fontsize=14)
plt.xlabel('Experience Aspect')
plt.ylabel('Number of Mentions')
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.7)

plt.tight_layout()
plt.show()

"""## Question C - LDA Topic Modelling

What are the main topics discussed in Airbnb guest reviews in Victoria?

How does the prevalence of these topics vary between the two most popular room types in the dataset, and

What do these differences suggest about guest expectations and experiences?
"""

import re
import math
import nltk
nltk.download('stopwords')
nltk.download('punkt_tab')
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.decomposition import LatentDirichletAllocation as LDA

# Load ALL reviews (no filtering) for LDA training
df_all = reviews.dropna(subset=['comments']).copy()
print(f"\nTotal reviews for LDA training: {len(df_all)}")

# Note: unlike Questions A and B where VADER required raw text,
# LDA requires cleaned text because it works on word co-occurrence frequencies.
# Stop words and punctuation would dominate every topic and produce meaningless results.

stop_words = stopwords.words('english')

def clean_text(text):
    try:
        # Remove everything except letters (same as lab)
        text = re.sub('[^A-Za-z]', ' ', str(text))
        # Make lowercase
        text = text.lower()
        # Tokenise
        tokens = text.split()
        # Remove short words — same threshold as lab (length > 3)
        tokens = [w for w in tokens if len(w) > 3]
        # Remove stop words
        tokens = [w for w in tokens if w not in stop_words]
        return ' '.join(tokens)
    except:
        return ''

# Clean ALL reviews — full corpus, no room type filter
Cleaned_doc = df_all['comments'].apply(clean_text).tolist()

print(f"Total cleaned documents: {len(Cleaned_doc)}")
print("\nSample cleaned review:")
print(Cleaned_doc[0])

count_vectorizer = CountVectorizer()
count_data = count_vectorizer.fit_transform(Cleaned_doc)
terms = count_vectorizer.get_feature_names_out()

# Count word frequencies across all documents
total_counts = np.zeros(len(terms))
for t in count_data:
    total_counts += t.toarray()[0]

# Plot top 40 most common words (same as lab)
count_dict = sorted(zip(terms, total_counts), key=lambda x: x[1], reverse=True)[0:40]
words = [w[0] for w in count_dict]
counts = [w[1] for w in count_dict]

plt.figure(2, figsize=(12, 4))
plt.subplot(title='40 Most Common Words')
plt.bar(words, counts)
plt.xticks(rotation=90)
plt.xlabel('Words')
plt.ylabel('Counts')
plt.tight_layout()
plt.show()

# Remove highly frequent (>20% of documents) and very rare (<0.5% of documents) words
# Highly frequent words appear in every topic and add no discriminating value
# Very rare words are statistically unreliable for topic modelling

n_docs = len(Cleaned_doc)
keepIndex = []
for t in range(len(total_counts)):
    if total_counts[t] < n_docs * 0.20 and total_counts[t] > n_docs * 0.005:
        keepIndex.append(t)

print(f'Number of terms retained: {len(keepIndex)}')
ReducedTerm = [terms[t] for t in keepIndex]
ReducedCount = count_data[:, keepIndex]

!pip install gensim

import gensim
import gensim.corpora as corpora
from gensim.models import CoherenceModel
from pprint import pprint

# Prepare gensim input format (same as lab)
Cleaned_doc_new = []
for doc in Cleaned_doc:
    tokens = [t for t in doc.split() if t in ReducedTerm]
    Cleaned_doc_new.append(tokens)

id2word = corpora.Dictionary(Cleaned_doc_new)
Corpus = [id2word.doc2bow(text) for text in Cleaned_doc_new]

print("Gensim corpus prepared.")
print(f"Dictionary size: {len(id2word)}")

# Test topic numbers 2–10 and compute coherence score for each
Topics = list(range(2, 11, 1))
coherence_scores = []
Trained_Models = []

for top in Topics:
    lda_model = gensim.models.ldamodel.LdaModel(
        corpus=Corpus,
        id2word=id2word,
        num_topics=top,
        iterations=50,
        passes=5,
        random_state=2026
    )
    Trained_Models.append(lda_model)
    coherence_model = CoherenceModel(
        model=lda_model,
        texts=Cleaned_doc_new,
        dictionary=id2word,
        coherence='c_v'
    )
    score = coherence_model.get_coherence()
    coherence_scores.append(score)
    print(f'Topic Number: {top} -- Coherence: {round(score, 4)}')

import matplotlib.pyplot as pyplot

# Plot coherence scores (same as lab)
pyplot.figure(figsize=(8, 4))
pyplot.plot(coherence_scores, marker='o')
pyplot.xticks(range(len(Topics)), Topics)
pyplot.title('Coherence Score by Number of Topics', fontsize=14)
pyplot.xlabel('Number of Topics')
pyplot.ylabel('Coherence Score')
pyplot.tight_layout()
pyplot.show()

best_k = Topics[np.argmax(coherence_scores)]
print(f"\nStatistically optimal number of topics: {best_k}")
print("3 topics will be used for final analysis — sufficient granularity for business interpretation.")

# Train Final LDA Model with 8 Topics on ALL Comments
number_topics = 3

lda = LDA(n_components=number_topics, n_jobs=-1, random_state=2026)
lda.fit(ReducedCount)

Word_Topics_Pro = lda.components_ / lda.components_.sum(axis=1)[:, np.newaxis]

for topic_idx, topic in enumerate(Word_Topics_Pro):
    print("\nTopic #%d:" % topic_idx)
    count_dict = (zip(ReducedTerm, topic))
    count_dict = sorted(count_dict, key=lambda x: x[1], reverse=True)[0:5]
    for w in count_dict:
        print(w[0], ': {0:.3f}'.format(w[1]))

# Mapping descriptive names for the 3-topic model
topic_names = {
    0: "Satisfaction & Recommendation",
    1: "Host Helpfulness & Check-in",
    2: "Location & Transit"
}

# Create a list of names for easy labeling in plots
topic_labels = [topic_names[i] for i in range(len(topic_names))]

print("Finalized Topic Names:")
for idx, name in topic_names.items():
    print(f"Topic {idx + 1}: {name}")

# Word Clouds for Each Topic
!pip install wordcloud
from wordcloud import WordCloud
import matplotlib.pyplot as pyplot


number_topics = 3

rows = math.ceil(number_topics / 4)
fig, ax = pyplot.subplots(rows, 4, figsize=(16, 4 * rows))
ax = np.array(ax).flatten()
[axi.set_axis_off() for axi in ax]

for topic_idx, topic in enumerate(Word_Topics_Pro):
    count_dict = sorted(zip(ReducedTerm, topic), key=lambda x: x[1], reverse=True)
    Word_Frequency = dict(count_dict[0:15])
    wordcloud = WordCloud(background_color="white").generate_from_frequencies(Word_Frequency)
    ax[topic_idx].imshow(wordcloud)
    ax[topic_idx].set_title(f"Topic {topic_idx + 1}: {topic_names[topic_idx]}", fontsize=13)
    ax[topic_idx].axis('on')

plt.tight_layout()
plt.savefig('topic_wordclouds.png', dpi=150)
plt.show()

# Compute topic distribution for every document in the full corpus
TopicDis_Doc = lda.transform(ReducedCount)

# Average across all documents to get overall topic prevalence
Overall_Topic_Dis = sum(TopicDis_Doc) / sum(sum(TopicDis_Doc))

Bar_index = np.asarray(range(1, number_topics + 1))

pyplot.figure(figsize=(7, 4))
pyplot.title('Overall Topic Popularity — Victoria Airbnb Reviews', fontsize=14)
pyplot.xlabel('Topic')
pyplot.ylabel('Probability')
pyplot.bar(Bar_index, Overall_Topic_Dis.tolist(), 0.4)
pyplot.xticks(Bar_index)
pyplot.tight_layout()
plt.savefig('topic_overall.png', dpi=150)
pyplot.show()

print("Overall topic distribution:")
for t in range(number_topics):
    print(f"  Topic {t+1}: {Overall_Topic_Dis[t]:.4f}")

# Identify top 2 room types by total number of reviews (consistent with Q A definition)
room_popularity = (listings.groupby('room_type')['number_of_reviews']
                   .sum()
                   .sort_values(ascending=False))
print("Room type popularity by total reviews:")
print(room_popularity)

top2_room_types = room_popularity.head(2).index.tolist()
print(f"\nTop 2 room types selected: {top2_room_types}")

# Step 1: Merge df_all with listings to get room_type
# This is done HERE — after LDA is fully trained on the complete corpus
df_merged = df_all.merge(
    listings[['id', 'room_type']],
    left_on='listing_id',
    right_on='id',
    how='inner'
)

# Keep only top 2 room types
df_top2 = df_merged[df_merged['room_type'].isin(top2_room_types)].copy()
print(f"Reviews for top 2 room types: {len(df_top2)}")
print(df_top2['room_type'].value_counts())

# Step 2: Clean the top 2 room type comments
Cleaned_doc_top2 = df_top2['comments'].apply(clean_text).tolist()

# Step 3: Vectorise using the SAME vocabulary from full corpus
# Use transform() NOT fit_transform() — critical to keep the same feature space
count_data_top2 = count_vectorizer.transform(Cleaned_doc_top2)
ReducedCount_top2 = count_data_top2[:, keepIndex]

# Step 4: Compare topic distributions by room type
room_types = ['Entire home/apt', 'Private room']
Group_Prob = []

for room in room_types:
    mask = (df_top2['room_type'] == room).values
    ReducedCount_Selected = ReducedCount_top2[mask]
    TopicDis = lda.transform(ReducedCount_Selected)
    Group_Prob.append(sum(TopicDis) / sum(sum(TopicDis)))

# Plot side by side
plt.figure(figsize=(12, 6))
plt.title('Topic Distribution by Room Type\n(Victoria Airbnb Reviews)', fontsize=14)
plt.ylabel('Probability')

width = 0.35
x = np.arange(len(topic_labels))

# Create the side-by-side bars
plt.bar(x - width/2, Group_Prob[0], width, label=room_types[0], color='#3498db')
plt.bar(x + width/2, Group_Prob[1], width, label=room_types[1], color='#e74c3c')

# Set x-ticks to the descriptive names from topic_labels
plt.xticks(x, topic_labels, rotation=0, ha='middle')

plt.legend()
plt.tight_layout()
plt.savefig('topic_by_roomtype.png', dpi=150)
plt.show()

# Print exact values for your report table
print("\nTopic probabilities by room type:")
for i, room in enumerate(room_types):
    print(f"\n{room}:")
    for t in range(number_topics):
        print(f"  {topic_names[t]}: {Group_Prob[i][t]:.4f}")